apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  type: NodePort
  selector:
    app: expense-tracker
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
